name: Deploy

on:
  push:
    branches: [ master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
      with:
        lfs: true

    - name: Deploy through SFTP
      uses: SamKirkland/FTP-Deploy-Action@3.0.0
      with:
        ftp-server: sftp://asmi.ro/var/www/smarthack
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        known-hosts: asmi.ro ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINRGXStIsKVReOc8426Vg+513V2iDwosyyk2+AA9Re6M
